# Define the "kata" runtime class
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1beta1
metadata:
  name: kata
handler: kata
overhead:
  podFixed:
    memory: "160Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
